repos:
  # Black
  - repo: https://github.com/psf/black
    rev: 24.10.0
    hooks:
      - id: black

  # isort
  - repo: https://github.com/pre-commit/mirrors-isort
    rev: v5.13.2
    hooks:
      - id: isort

  # flake8
  - repo: https://github.com/pycqa/flake8
    rev: 7.1.1
    hooks:
      - id: flake8
