repos:
- repo: local
  hooks:
    # flake8
    - id: flake8
      name: flake8
      entry: flake8 .
      language: system
      types_or: [ python, pyi ]
      require_serial: true
      pass_filenames: false

    # isort
    - id: isort
      name: isort
      entry: isort .
      language: system
      types_or: [ python, pyi ]
      require_serial: true
      pass_filenames: false

    # black
    - id: black
      name: black
      entry: black .
      language: system
      types_or: [ python, pyi ]
      require_serial: true
      pass_filenames: false

    # mypy
    - id: mypy
      name: mypy
      entry: mypy src/
      language: system
      types_or: [ python, pyi ]
      require_serial: true
      pass_filenames: false
      
  
